<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	Description: Language phrases for event logger plugin


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

return array(
	'dir_not_found' => 'This directory cannot be found. Please enter the full path.',
	'dir_not_writable' => 'This directory is not writable by the web server. Please choose a different directory, use chown/chmod to change permissions, or contact your web hosting company for assistance.',
	'enter_directory' => 'This is a file. Please enter the full path of a directory.',
	'extras' => 'extras...',
	'header_lines' => 'Include header lines at top of each log file',
	'log_events_daily' => 'Log events to daily log files',
	'log_events_x_table' => 'Log events to ^ database table',
	'log_files_dir' => 'Directory for log files - enter full path:',
	'q2a_x_log_file_generated' => 'Question2Answer ^ log file generated by Event Logger plugin.',
	'specify_dir_writable' => 'Please specify a directory that is writable by the web server.',
	'tab_delimited_file' => 'This file is formatted as tab-delimited text with UTF-8 encoding.',
);
