<?php
	
/*
	Question2Answer 1.4 (c) 2011, Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-main.php
	Version: 1.4
	Date: 2011-06-17 12:46:02 GMT
	Description: Language phrases commonly used throughout Q2A


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer' => '1 respuesta',
		'1_comment' => "1 comentario",
		'1_day' => '1 día',
		'1_disliked' => '1 negativo',
		'1_flag' => "1 marca",
		'1_hour' => '1 hora',
		'1_liked' => '1 positivo',
		'1_minute' => '1 minuto',
		'1_month' => '1 mes',
		'1_point' => '1 punto',
		'1_question' => '1 pregunta',
		'1_second' => '1 segundo',
		'1_user' => "1 usuario",
		'1_view' => "1 vista",
		'1_vote' => '1 voto',
		'1_week' => '1 semana',
		'1_year' => '1 año',
		'all_categories' => 'Todas las categorías',
		'anonymous' => 'anónimo',
		'answer_edited' => 'respuesta editada',
		'answered' => 'respondido',
		'answered_qs_title' => "Preguntas más contestadas",
		'asked' => 'preguntado',
		'by_x' => 'por ^',
		'cancel_button' => 'Cancelar',
		'comment_edited' => 'comentario editado',
		'commented' => 'comentado',
		'edited' => 'editado',
		'field_required' => 'Por favor, introduce algo en este campo',
		'general_error' => 'Ha ocurrido un error en el servidor - por favor, vuélvelo a intentar.',
		'highest_users' => 'Usuarios mejor puntuados',
		'hot_qs_title' => "Preguntas más activas",
		'image_not_read' => "La imagen podría no ser leída. Por favor suba una de: ^",
		'image_too_big_x_pc' => "Esta imagen es demasiado grande. Por favor escalela a ^% e intentelo de nuevo.",
		'in_category_x' => 'en ^',
		'ip_address_x' => 'Dirección IP ^',
		'logged_in_x' => 'Hola ^',
		'max_length_x' => 'La longitud máxima son ^ caracteres',
		'me' => 'mí',
		'meta_order' => '^what^who^when^where', // sets order of elements like: <answered> <15 hours ago> <in Problems> <by me (500 points)>
		'min_length_x' => 'Por favor, proporciona más información (al menos ^ caracteres)',
		'nav_account' => 'Mi cuenta',
		'nav_activity' => 'Toda la actividad',
		'nav_admin' => 'Admin',
		'nav_ask' => 'Hacer una pregunta',
		'nav_categories' => 'Categorías',
		'nav_hot' => "Más activas",
		'nav_feedback' => 'Enviar feedback',
		'nav_home' => 'Inicio',
		'nav_login' => 'Ingresar',
		'nav_logout' => 'Salir',
		'nav_most_answers' => "Más contestadas",
		'nav_most_recent' => "Recientes",
		'nav_most_views' => "Más vistas",
		'nav_most_votes' => "Más votadas",
		'nav_qa' => 'Q&A',
		'nav_qs' => 'Preguntas',
		'nav_register' => 'Registro',
		'nav_tags' => 'Etiquetas',
		'nav_unanswered' => 'Sin responder',
		'nav_users' => 'Usuarios',
		'no_active_users' => 'No se han encontrado usuarios activos',
		'no_answers_found' => 'No se han encontrado respuestas',
		'no_answers_in_x' => 'No se han encontrado respuestas en ^',
		'no_categories_found' => 'No se han encontrado categorías',
		'no_category' => 'No hay categorías',
		'no_comments_found' => 'No se han encontrado comentarios',
		'no_comments_in_x' => 'No se han encontrado comentarios en ^',
		'no_questions_found' => 'No se han encontrado preguntas',
		'no_questions_in_x' => "Ninguna pregunta en ^",
		'no_related_qs_title' => 'No se han encontrado preguntas relacionadas',
		'no_results_for_x' => 'No se han encontrado resultados para ^',
		'no_tags_found' => 'No se han encontrado etiquetas',
		'no_una_questions_found' => 'No se han encontrado preguntas sin contestar',
		'page_label' => 'Página:',
		'page_next' => 'Siguiente',
		'page_not_found' => 'Página no encontrada',
		'page_prev' => 'Anterior',
		'popular_tags' => 'Etiquetas más populares',
		'questions_tagged_x' => 'Preguntas recientes etiquetadas ^',
		'recent_activity_in_x' => 'Actividad reciente en ^',
		'recent_activity_title' => 'Actividad reciente',
		'recent_as_in_x' => 'Preguntas respondidas recientes en ^',
		'recent_as_title' => 'Preguntas respondidas recientemente',
		'recent_cs_in_x' => 'Comentarios añadidos recientemente en ^',
		'recent_cs_title' => 'Comentarios añadidos recientemente',
		'recent_qs_as_in_x' => 'Preguntas y respuestas recientes en ^',
		'recent_qs_as_title' => 'Preguntas y respuestas recientes',
		'recent_qs_in_x' => 'Preguntas recientes en ^',
		'recent_qs_title' => 'Preguntas recientes',
		'related_qs_title' => 'Preguntas relacionadas',
		'results_for_x' => 'Buscar resultados para ^',
		'save_button' => 'Guardar cambios',
		'search_button' => 'Buscar',
		'search_title' => 'Buscar preguntas',
		'send_button' => 'Enviar',
		'suggest_ask' => 'Participa en la comunidad empezando por ^1proponer una pregunta^2.',
		'suggest_category_qs' => 'Para ver más, presiona en todas las ^1preguntas en esta categoría^2.',
		'suggest_qs_tags' => 'Para ver más, presiona en ^1lista completa de preguntas^2 o ^3etiquetas populares^4.',
		'suggest_qs' => 'Para ver más, presiona para la ^1lista completa de preguntas^2.',
		'unanswered_qs_in_x' => 'Preguntas recientes sin respuesta en ^',
		'unanswered_qs_title' => 'Preguntas recientes sin respuestas',
		'upload_limit' => "Demasiadas subidas - por favor intentelo de nuevo en una hora",
		'viewed_qs_title' => "Preguntas más vistas",
		'view_q_must_confirm' => "Por favor ^5confirme su email^6 para ver la página de preguntas.",
		'view_q_must_login' => "Por favor ^1inicie sesión^2 o ^3registrese^4 para ver las páginas de preguntas.",
		'vote_disabled_hidden_a' => 'No puedes votar a respuestas ocultas',
		'vote_disabled_hidden_q' => 'No puedes votar a preguntas ocultas',
		'vote_disabled_level' => "Sólo pueden votar algunos usuarios",
		'vote_disabled_my_a' => 'No puedes votar tus propias respuestas',
		'vote_disabled_my_q' => 'No puedes votar tus propias preguntas',
		'vote_disabled_q_page_only' => 'Por favor, consulta la pregunta para votar',
		'vote_down_popup' => 'Presiona para votar negativo',
		'vote_limit' => 'Demasiados votos recibidos - por favor, vuélvelo a intentar en una hora',
		'vote_must_confirm' => 'Por favor ^5confirma tu correo electrónico^6 para votar.',
		'vote_must_login' => 'Por favor ^1ingresa^2 o ^3regístrate^4 para votar.',
		'vote_not_allowed' => 'Votar sobre esto no esta permitido',
		'vote_up_popup' => 'Presiona para votar positivo',
		'voted_down_popup' => 'Has votado negativo - presiona para quitar el voto',
		'voted_qs_title' => "Preguntas más votadas",
		'voted_up_popup' => 'Has votado positivo - presiona para quitar el voto',
		'x_ago' => 'hace ^',
		'x_answers' => '^ respuestas',
		'x_comments' => "^ comentarios",
		'x_days' => '^ días',
		'x_disliked' => '^ negativos',
		'x_flags' => "^ marcas",
		'x_hours' => '^ horas',
		'x_liked' => '^ positivos',
		'x_minutes' => '^ minutos',
		'x_months' => '^ meses',
		'x_points' => '^ puntos',
		'x_questions' => '^ preguntas',
		'x_seconds' => '^ segundos',
		'x_users' => "^ usuarios",
		'x_views' => "^ vistas",
		'x_votes' => '^ votos',
		'x_weeks' => '^ semanas',
		'x_years' => '^ años',
		'1_tag' => "1 etiqueta",
		'add_category_x_favorites' => "Añadir categoría ^ a mis favoritos",
		'add_favorites' => "Añadir a mis favoritos",
		'add_tag_x_favorites' => "Añadir etiqueta ^ a mis favoritos",
		'answer_reshown' => "respuesta mostrada de nuevo",
		'answer_selected' => "respuesta seleccionada",
		'answered_qs_in_x' => "Preguntas más respondidas en ^",
		'asked_related_q' => "pregunta relacionada",
		'closed' => "cerrada",
		'comment_moved' => "comentario movido",
		'comment_reshown' => "comentario mostrado de nuevo",
		'date_day_min_digits' => "1",
		'date_format_other_years' => "^month ^day, ^year",
		'date_format_this_year' => "^month ^day",
		'date_month_1' => "Ene",
		'date_month_2' => "Feb",
		'date_month_3' => "Mar",
		'date_month_4' => "Abr",
		'date_month_5' => "May",
		'date_month_6' => "Jun",
		'date_month_7' => "Jul",
		'date_month_8' => "Ago",
		'date_month_9' => "Sep",
		'date_month_10' => "Oct",
		'date_month_11' => "Nov",
		'date_month_12' => "Dic",
		'date_year_digits' => "4",
		'hidden' => "oculto",
		'hot_qs_in_x' => "Preguntas más activas en ^",
		'moved' => "movido",
		'nav_no_answer' => "Sin respuesta",
		'nav_no_selected_answer' => "Sin respuesta seleccionada",
		'nav_no_upvoted_answer' => "Sin respuesta con voto positivo",
		'nav_updates' => "Mis Actualizaciones",
		'no_una_questions_in_x' => "Sin preguntas no respondidas en ^",
		'no_unselected_qs_found' => "No hay preguntas sin una respuesta seleccionada",
		'no_unupvoteda_qs_found' => "No hay preguntas sin respuestas con voto positivo",
		'recategorized' => "recategorizada",
		'remove_favorites' => "Remover de mis favoritos",
		'remove_x_favorites' => "Remover ^ de mis favoritos",
		'reopened' => "reabierta",
		'reshown' => "mostrada de nuevo",
		'retagged' => "reetiquetada",
		'search_explanation' => "Por favor ingresa texto en el cuadro de búsqueda y trata nuevamente.",
		'selected' => "seleccionada",
		'unselected_qs_in_x' => "Preguntas sin una respuesta seleccionada en ^",
		'unselected_qs_title' => "Preguntas recientes sin una respuesta seleccionada",
		'unupvoteda_qs_in_x' => "Preguntas sin una respuesta con voto positivo en ^",
		'unupvoteda_qs_title' => "Preguntas recientes sin una respuesta con voto positivo",
		'viewed_qs_in_x' => "Preguntas más vistas en ^",
		'vote_disabled_down' => "Voto negativo sólo disponible para algunos usuarios",
		'vote_down_must_confirm' => "Por favor ^5confirma tu correo electrónico^6 para votar negativo.",
		'voted_qs_in_x' => "Preguntas más votadas en ^",
		'x_tags' => "^ etiquetas",
		'max_upload_size_x' => 'El tamaño máximo para subir archivos es ^',
		'view_q_must_be_approved' => 'Tu cuenta debe primero ser aprobada para ver páginas de preguntas.',
		'vote_disabled_approve' => 'Tu cuenta debe primero ser aprobada antes de que puedas votar',
		'vote_disabled_down_approve' => 'Tu cuenta debe ser aprobada antes de que puedas votar negativamente',

	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
