<?php
	
/*
	Question2Answer 1.4 (c) 2011, Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-options.php
	Version: 1.4
	Date: 2011-06-17 12:46:02 GMT
	Description: Language phrases for all options, as shown in admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'allow_change_usernames' => "Permitir a los usuarios con publicaciones cambiar sus nombres de usuario:",
		'allow_multi_answers' => 'Permitir múltiples respuesta por usuario:',
		'allow_no_category' => 'Permitir preguntas sin categoría',		
		'allow_no_sub_category' => "Permitir preguntas con categoría pero sin subcategoría:",
		'allow_private_messages' => "Permitir a los usuarios enviar mensajes privados:",
		'allow_view_q_bots' => "Permitir a los motores de busqueda ver las páginas de preguntas:",
		'avatar_allow_gravatar' => 'Permitir imágenes de perfil ^1Gravatar^2:',
		'avatar_allow_upload' => 'Permitir a los usuarios añadir imágenes de perfil:',
		'avatar_default_show' => 'Mostrar imagen de perfil por defecto:',
		'avatar_profile_size' => 'Tamaño de la imagen de perfil en la página de perfil de usuario (píxeles):',
		'avatar_q_list_size' => 'Tamaño de las imágenes de perfil en las listas de preguntas (píxeles):',
		'avatar_q_page_a_size' => 'Tamaño de las imágenes de perfil en las respuestas (píxeles):',
		'avatar_q_page_c_size' => 'Tamaño de las imágenes de perfil en los comentarios (píxeles):',
		'avatar_q_page_q_size' => 'Tamaño de las imágenes de perfil en las preguntas (píxeles):',
		'avatar_store_size' => 'Tamaño máximo de las imágenes de perfil añadidas (píxeles):',
		'avatar_users_size' => 'Tamaño de las imágenes de perfil en la zona superior de la página de usuario (píxeles):',
		'block_bad_words' => 'Palabras censuradas (separadas por espacios o comas):',
		'block_ips_write' => 'Direcciones IP bloqueadas (separadas por espacios o comas):',
		'captcha_on_anon_post' => 'Utiliza reCAPTCHA para entradas anónimas:',
		'captcha_on_feedback' => 'Utiliza reCAPTCHA en el formulario de feedback:',
		'captcha_on_register' => 'Utiliza reCAPTCHA para el registro de usuarios:',
		'captcha_on_reset_password' => 'Utiliza reCAPTCHA en el formulario de nueva contraseña:',
		'captcha_on_unconfirmed' => 'Utiliza reCAPTCHA para entradas si el correo electrónico no ha sido confirmado:',
		'columns_tags' => 'Columnas para la página de etiquetas:',
		'columns_users' => 'Columnas para la página de usuarios:',
		'comment_on_as' => 'Permitir comentarios en las respuestas:',
		'comment_on_qs' => 'Permitir comentarios en las preguntas:',
		'confirm_user_emails' => 'Requiere confirmación del correo electrónico del usuario:',
		'custom_home_content' => 'Contenido para mostra en la página de inicio (permite HTML):',
		'custom_home_heading' => 'Cabecera para mostrar en la zona superior de la página de inicio:',
		'default_privacy' => 'Privacidad: Tu correo electrónico no será compartido o vendido a terceros.',
		'default_sidebar' => "Bienvenido a ^, donde puedes realizar preguntas y recibir respuestas de otros miembros de la comunidad.",
		'default_suffix' => 'Q&A',
		'do_ask_check_qs' => 'Comprobar si existen preguntas similares al publicar:',
		'do_complete_tags' => 'Mostrar etiquetas sugeridas mientras se escribe:',
		'do_count_q_views' => "Contar el número de preguntas vistas:",
		'do_example_tags' => 'Mostrar etiquetas de ejemplo basadas en la pregunta:',
		'editor_for_as' => 'Editor por defecto para las respuestas:',
		'editor_for_cs' => 'Editor por defecto para los comentarios:',
		'editor_for_qs' => 'Editor por defecto para las preguntas:',
		'email_privacy' => 'Nota de privacidad para correos electrónicos en todos los formularios (permite HTML):',
		'feed_for_activity' => "Fuente para actividad reciente:",
		'feed_for_qa' => 'Fuente para preguntas y respuestas recientes:',
		'feed_for_questions' => 'Fuente para preguntas recientes:',
		'feed_for_search' => 'Fuente para resultados de búsqueda:',
		'feed_for_tag_qs' => 'Fuente para preguntas recientes de cada etiqueta:',
		'feed_for_unanswered' => 'Fuente para preguntas recientes sin respuesta:',
		'feed_full_text' => 'Incluir texto completo en las fuentes:',
		'feed_number_items' => 'Número máximo de elementos en las fuentes:',
		'feed_per_category' => 'Fuentes para todo lo anterior en cada categoría:',
		'feedback_email' => 'Correo electrónico para los mensajes de administración (no se muestra a los usuarios):',
		'feedback_enabled' => 'Proporcionar un formulario a los usuarios para enviar feedback',
		'flagging_hide_after' => "Ocultar automáticamente las publicacione que llegan:",
		'flagging_notify_every' => "Enviarme un email después de cada adición:",
		'flagging_notify_first' => "Enviarme un email primero una vez se reciba la publicación:",
		'flagging_of_posts' => "Permitir poner la marca de inapropiado a las publicaciones:",
		'follow_on_as' => 'Permitir nuevas preguntas relacionadas a respuestas:',
		'from_email' => 'Dirección de envío para todos los mensajes de administración:',
		'hot_weight_a_age' => "Peso relativo de la antiguiedad de la última respuesta para las más activas:",
		'hot_weight_answers' => "Peso relativo del numero de respuestas para las más activas:",
		'hot_weight_q_age' => "Peso relativo de la antiguedad de la pregunta para las más activas:",
		'hot_weight_views' => "Peso relativo del numero de vistas para las más activas:",
		'hot_weight_votes' => "Peso relativo de los votos para las más activas:",
		'links_in_new_window' => "Abrir los enlaces en una ventana nueva:",
		'logo_height' => 'Altura del logotipo en píxeles:',
		'logo_show' => 'Muestra un logotipo en la cabecera de la página',
		'logo_url' => 'URL del logotipo (ruta absoluta o relativa a la raíz QA):',
		'logo_width' => 'Anchura del logotipo en píxeles:',
		'match_1' => 'Más específico',
		'match_2' => 'Específico',
		'match_3' => 'Por defecto',
		'match_4' => 'General',
		'match_5' => 'Más general',
		'match_ask_check_qs' => 'Coincidencias de preguntas similares:',
		'match_example_tags' => 'Coincidencias de etiquetas de ejemplo:',
		'match_related_qs' => 'Coincidencias de preguntas relacionadas:',
		'max_len_q_title' => 'Caracteres máximos en el título de la pregunta:',
		'max_num_q_tags' => 'Máximas etiquetas para una pregunta:',
		'max_rate_ip_as' => 'Máximas respuestas por dirección IP cada hora:',
		'max_rate_ip_cs' => 'Máximos comentarios por dirección IP cada hora:',
		'max_rate_ip_flags' => "Marcas máximas por IP en una hora:",
		'max_rate_ip_logins' => 'Máximos intentos de ingreso por dirección IP cada hora:',
		'max_rate_ip_messages' => "Máximos mensajes privados por IP en una hora:",
		'max_rate_ip_qs' => 'Máximas preguntas por dirección IP cada hora:',
		'max_rate_ip_uploads' => "Maximas subidas por IP en una hora:",
		'max_rate_ip_votes' => 'Máximos votos por dirección IP cada hora:',
		'max_rate_user_as' => 'Máximas respuestas por usuario cada hora:',
		'max_rate_user_cs' => 'Máximos comentarios por usuario cada hora:',
		'max_rate_user_flags' => "Marcas máximas por usuario en una hora:",
		'max_rate_user_messages' => "Máximos mensajes privados por usuario en una hora:",
		'max_rate_user_qs' => 'Máximas preguntas por usuario cada hora:',
		'max_rate_user_uploads' => "Máximas subidas por usuario en una hora:",
		'max_rate_user_votes' => 'Máximos votos por usuario cada hora:',
		'min_len_a_content' => 'Mínimos caracteres en una respuesta:',
		'min_len_c_content' => 'Mínimos caracteres en un comentario:',
		'min_len_q_content' => 'Mínimos caracteres en el cuerpo de la pregunta:',
		'min_len_q_title' => 'Mínimos caracteres en el título de una pregunta:',
		'min_num_q_tags' => 'Mínimo número de etiquetas en una pregunta:',
		'neat_urls' => 'Estructura URL para las páginas de tu sitio web:',
		'notify_admin_q_post' => 'Notificarme por correo electrónico cuando una pregunta es publicada',
		'notify_users_default' => "Revisar las notificaciones por defecto:",
		'page_size_activity' => "Longitud de la página de Todas las actividades:",
		'page_size_ask_check_qs' => 'Máximas preguntas similares a mostrar:',
		'page_size_ask_tags' => 'Máximas sugerencias de etiquetas a mostrar:',
		'page_size_home' => 'Longitud de la página de inicio:',
		'page_size_hot_qs' => "Longitud de la página de Más activas:",
		'page_size_qs' => 'Longitud de la página de preguntas:',
		'page_size_related_qs' => 'Máximo de preguntas relacionadas:',
		'page_size_search' => 'Preguntas en la página de búsqueda:',
		'page_size_tag_qs' => 'Preguntas en la página de etiquetas:',
		'page_size_tags' => 'Longitud de la página de etiquetas:',
		'page_size_una_qs' => 'Longitud de la página de preguntas sin respuesta:',
		'page_size_users' => 'Longitud de la página de usuario:',
		'pages_prev_next' => 'Enlaces a páginas Anterior/Siguiente:',
		'permit_admins' => 'Administradores',
		'permit_all' => 'Cualquiera',
		'permit_block' => 'Bloquear o desbloquear usuarios o IPs:',
		'permit_confirmed' => 'Usuarios registrados con correo electrónico confirmado',
		'permit_create_admins' => 'Creación de administradores:',
		'permit_create_eds_mods' => 'Creación de editores y moderadores:',
		'permit_create_experts' => 'Creación de expertos:',
		'permit_editors' => 'Editores, Moderadores, Administradores',
		'permit_experts' => 'Expertos, Editores, Moderadores, Administradores',
		'permit_moderators' => 'Moderadores y Administradores',
		'permit_points' => "Usuarios registrados con suficientes puntos",
		'permit_points_confirmed' => "Registrados & email confirmado & suficientes puntos",
		'permit_see_emails' => 'Mostrar correo electrónico del usuario:',
		'permit_supers' => 'Super Administradores',
		'permit_users' => 'Usuarios registrados',
		'place_full_below_content' => "Ancho completo - Debajo de contenido",
		'place_full_below_footer' => "Ancho completo - Debajo del pie de página",
		'place_full_below_nav' => "Ancho completo - Debajo de navegación",
		'place_full_top' => "Ancho completo - En lo alto de la página",
		'place_main_below_lists' => "Área principal- Debajo de listas",
		'place_main_below_title' => "área principal - Debajo de título",
		'place_main_bottom' => "Área principal - Abajo",
		'place_main_top' => "Área principal- Arriba",
		'place_side_below_categories' => "Panel lateral - Debajo de categorías",
		'place_side_below_sidebar' => "Panel lateral - Debajo de la barra lateral",
		'place_side_last' => "Panel lateral - Último",
		'place_side_top' => "Panel lateral - Arriba",
		'points_a_selected' => 'Tener tu respuesta seleccionada como la mejor:',
		'points_a_voted_max_gain' => 'Límite de votos positivos en cada respuesta:',
		'points_a_voted_max_loss' => 'Límite de votos negativos en cada respuesta:',
		'points_base' => 'Añadido a todos los usuarios:',
		'points_multiple' => 'Multiplicar todos los puntos:',
		'points_post_a' => 'Publicar una respuesta:',
		'points_post_q' => 'Publicar una pregunta:',
		'points_q_voted_max_gain' => 'Límite de votos positivos para cada pregunta:',
		'points_q_voted_max_loss' => 'Límite de votos negativos para cada pregunta:',
		'points_select_a' => 'Selección de la mejor respuesta para tu pregunta:',
		'points_vote_down_a' => 'Votar negativo una respuesta:',
		'points_vote_down_q' => 'Votar negativo una pregunta:',
		'points_vote_up_a' => 'Votar positivo una respuesta:',
		'points_vote_up_q' => 'Votar positivo una pregunta:',
		'q_urls_remove_accents' => "Quitar acentos de las URLs de preguntas:",
		'q_urls_title_length' => "Longitud del título de la pregunta en las URLs:",
		'show_a_form_immediate' => 'Mostrar el formulario de respuesta inmediatamente:',
		'show_always' => 'Siempre',
		'show_c_reply_buttons' => 'Mostrar botones de respuesta en los comentarios:',
		'show_custom_footer' => 'HTML personalizado al final de cada página:',
		'show_custom_header' => 'HTML personalizado al inicio de cada página:',
		'show_custom_home' => 'Contenido personalizado en la página de inicio (sustituyendo a Q&A)',
		'show_custom_in_head' => 'HTML personalizado en el <HEAD> de cada página:',
		'show_custom_sidebar' => 'HTML personalizado en la barra lateral de cada página:',
		'show_custom_sidepanel' => 'HTML personalizado en el panel lateral de cada página:',
		'show_home_description' => 'Incluir descripción <META> en la página de inicio:',
		'show_if_no_as' => 'Si no hay respuestas',
		'show_never' => 'Nunca',
		'show_selected_first' => 'Mover la respuesta seleccionada a la parte superior:',
		'show_url_links' => 'Detectar y enlazar URLs en el texto introducido:',
		'show_user_points' => 'Mostrar puntos siguiendo al nombre de usuario:',
		'show_user_titles' => 'Mostrar títulos siguiendo al nombre de usuario:',
		'show_view_counts' => "Mostrar el número de preguntas vistas:",
		'show_view_count_q_page' => 'Mostrar el número de preguntas en páginas de preguntas:',
		'show_when_created' => 'Mostrar antiguedad del contenido del usuario:',
		'suspend_register_users' => "Suspendido temporalmente los nuevos registros:",
		'site_language' => 'El idioma para la interfaz de tu sitio web:',
		'site_maintenance' => 'Dejar el sitio web innaccesible para mantenimiento',
		'site_theme' => 'El tema visual para tu sitio web:',
		'site_title' => 'El nombre de tu sitio web para los títulos de página:',
		'site_url' => 'La URL a usar cuando se nombra tu sitio web:',
		'sort_answers_by' => 'Ordenar respuestas por:',
		'sort_time' => 'Tiempo',
		'sort_votes' => 'Votos',
		'tags_or_categories' => 'Clasificar preguntas utilizando:',
		'tag_separator_comma' => "Usar sólo la coma como separador de etiquetas:",
		'votes_separated' => 'Mostrar separados los votos positivos y negativos:',
		'voting_on_as' => 'Permitir votar respuestas:',
		'voting_on_q_page_only' => 'Permitir votar sólo en la página de la pregunta:',
		'voting_on_qs' => 'Permitir votos en las preguntas:',
		'allow_close_questions' => "Permitir que las preguntas sean cerradas manualmente:",
		'allow_login_email_only' => "Ingreso sólo con el correo electrónico (no con el nombre de usuario):",
		'allow_self_answer' => "Permitir a los usuarios responder sus propias preguntas:",
		'captcha_module' => "Usar el módulo captcha:",
		'confirm_user_required' => "Nuevos usuarios deben completar confirmación:",
		'default_subject' => "Un mensaje de ^",
		'do_close_on_select' => "Cerrar preguntas con una respuesta seleccionada:",
		'extra_field_active' => "Campo personalizado para información extra en el formulario de preguntas:",
		'extra_field_display_label' => "Mostrar la información extra en páginas de preguntas con rótulo:",
		'extra_field_display' => "Mostrar la información extra en páginas de preguntas",
		'feed_for_hot' => "Fuente para preguntas más activas:",
		'mailing_body' => "Texto del mensaje:",
		'mailing_enabled' => "Habilitar mailings masivos para todos los usuarios",
		'mailing_from_email' => "Desde (correo electrónico):",
		'mailing_from_name' => "Desde (nombre):",
		'mailing_per_minute' => "Velocidad máxima del mailing:",
		'mailing_subject' => "Asunto:",
		'max_rate_ip_registers' => "Velocidad límite para el registro de usuarios:",
		'moderate_anon_post' => "Usar moderación con entradas anónimas:",
		'moderate_by_points' => "Usar moderación con usuarios con pocos puntos:",
		'moderate_notify_admin' => "Enviarme un correo electrónico cuando una entrada necesite moderación:",
		'moderate_points_limit' => "Usar moderación con usuarios con menos de:",
		'moderate_unconfirmed' => "Usar moderación si el correo electrónico no ha sido confirmado:",
		'option_default' => "Por defecto",
		'page_size_q_as' => "Máximo de respuestas por página:",
		'permit_delete_users' => "Borrando usuarios:",
		'points_per_a_voted_down' => "Por voto negativo en tu respuesta:",
		'points_per_a_voted_up' => "Por voto positivo en tu respuesta:",
		'points_per_q_voted_down' => "Por voto negativo en tu pregunta:",
		'points_per_q_voted_up' => "Por voto positivo en tu pregunta:",
		'search_module' => "Usar módulo de búsqueda:",
		'show_custom_answer' => "Mensaje personalizado en formulario de respuestas - HTML permitido:",
		'show_custom_ask' => "Mensaje personalizado en formulario de preguntas - HTML permitido:",
		'show_custom_comment' => "Mensaje personalizado en formulario de comentarios - HTML permitido:",
		'show_custom_register' => "Mensaje personalizado en formulario de registro- HTML permitido:",
		'show_custom_welcome' => "Mensaje personalizado en correo electrónico enviado a nuevos usuarios registrados:",
		'show_fewer_cs_count' => "Si parcialmente oculto, mostrar más reciente:",
		'show_fewer_cs_from' => "Ocultar comentarios parcialmente si hay más de:",
		'show_full_date_days' => "Mostrar fecha completa luego de:",
		'show_message_history' => "Almacenar y mostrar el historial de mensajes privados:",
		'show_notice_visitor' => "Mensaje en la parte superior para visitas que llegan por primera vez - HTML permitido:",
		'show_notice_welcome' => "Mensaje en la parte superior para nuevos usuarios registrados - HTML permitido:",
		'site_theme_mobile' => "Tema para celulares:",
		'smtp_active' => "Enviar correo electrónico vía SMTP en vez de local mail",
		'smtp_address' => "Dirección del servidor SMTP:",
		'smtp_authenticate' => "Enviar nombre de usuario y contraseña de SMTP",
		'smtp_password' => "Contraseña de SMTP:",
		'smtp_port' => "Puerto de servidor de SMTP:",
		'smtp_secure_none' => "Ninguno",
		'smtp_secure' => "Conexión segura de SMTP:",
		'smtp_username' => "Nombre de usuario de SMTP:",
		'allow_user_walls' => "Permitir las publicaciones en los muros de los perfiles de usuario:",
		'approve_user_required' => "Todos los nuevos usuarios deben ser aprobados:",
		'avatar_message_list_size' => "Tamaño del avatar en listas de mensaje:",
		'captcha_on_unapproved' => "Usar captcha si el usuario no ha sido aprobado aún:",
		'moderate_edited_again' => "Volver a moderar publicaciones después de que estas sean modificadas:",
		'moderate_unapproved' => "Usar moderación si el usuario no ha sido aprobado aún:",
		'moderate_update_time' => "Tiempo que se mostrará en publicaciones moderadas:",
		'moderate_users' => "Habilitar moderación (aprobación) de usuarios:",
		'page_size_wall' => "Número de publicaciones de muro por página:",
		'permit_approve_users' => "Aprobando usuarios registrados:",
		'permit_approved' => "Usuarios aprobados únicamente",
		'permit_approved_points' => "Usuarios aprobados con suficientes puntos",
		'register_notify_admin' => "Enviarme un email cuando un nuevo usuario se registre:",
		'time_approved' => "Tiempo aprobado",
		'time_written' => "Tiempo escrito",
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
