<?php
	
/*
	Question2Answer 1.4 (c) 2011, Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-admin.php
	Version: 1.4
	Date: 2011-06-17 12:46:02 GMT
	Description: Language phrases for admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'active_widgets_explanation' => "Los siguientes widgets estan actualmente activos:",
		'add_category_button' => 'Añadir categoría',
		'add_field_button' => 'Añadir campo',
		'add_link_button' => 'Añadir enlace',
		'add_link_link' => ' - ^1añadir enlace^2',
		'add_new_field' => 'Añadir nuevo campo',
		'add_new_title' => 'Añadir nuevo título',
		'add_page_button' => 'Añadir página',
		'add_title_button' => 'Añadir título',
		'add_widget_button' => "Añadir Widget",
		'add_widget_link' => " - ^1añadir widget^2",
		'admin_title' => 'Administración',
		'after_footer' => 'Enlaces después del pie',
		'after_main_menu' => 'Después de las pestañas de la zona superior',
		'after_x_tab' => 'Después de la pestaña "^"',
		'after_x' => 'Después de "^"',
		'basic_editor' => 'Editor básico',
		'before_main_menu' => 'Antes de las pestañas de la zona superior',
		'block_ips_note' => 'Usa un guión medio para rangos o * para representar cualquier número. Ejemplos: 192.168.0.4 , 192.168.0.0-192.168.0.31 , 192.168.0.*',
		'block_words_note' => 'Usa un * para representar cualquier letra. Ejemplos: sol (seleccionará sólo la palabra exacta sol) , sol* (seleccionará sol o soleado) , so*l (seleccionará sol, soal, social).',
		'categories_introduction' => 'Para empezar a añadir categorías, presiona el botón \'Añadir categoría\'.',
		'categories_not_shown' => 'Algunas preguntas tienen categorías que no se mostrarán.',
		'categories_title' => 'Categorías',
		'categories' => 'Categorías',
		'category_add_sub' => "añadir subcategoría",
		'category_added' => "Categoría añadida",
		'category_already_used' => 'Ya está siendo utilizado por una categoría',
		'category_default_slug' => 'categoría-^',
		'category_description' => "Descripción de la categoría (opcional):",
		'category_max_depth_x' => "Algunas opciones se puede ocultar para prevenir que una categoría tenga más profundidad de ^ niveles.",
		'category_move_parent' => "mover a diferente padre",
		'category_name_first' => 'Nombre de la primera categoría:',
		'category_name' => 'Nombre de la categoría:',
		'category_no_add_subs_x' => "Esta categoría no puede tener subcategorías porque ya tiene  ^ niveles.",
		'category_no_delete_subs' => "Esta categoría no se puede borrar porque tiene una subcategoría.",
		'category_no_sub_error' => "^q las preguntas en esta categoría no tienen subcategorías - ^1cree la subcategoría^2",
		'category_no_sub_to' => "Mover las preguntas en ^ que no tengan subcategoría a:",
		'category_no_subs' => "Ninguna",
		'category_none_error' => "^q Las preguntas actuales no tienen categoría - ^1asigne una categoría^2",
		'category_none_to' => "Mover preguntas sin categoría a:",
		'category_parent' => "Categoría padre:",
		'category_saved' => "Categoría guardada",
		'category_subs' => "Subcategorías:",
		'category_slug' => 'Alias de la categoría (fragmento en la URL):',
		'category_top_level' => "Ningún padre (nivel alto)",
		'click_name_edit' => 'Páginas o enlaces personalizados:',
		'database_cleanup' => 'Acciones para la limpieza de la Base de Datos',
		'delete_category_reassign' => 'Borrar esta categoría y reasignar sus preguntas a:',
		'delete_category' => 'Borrar esta categoría',
		'delete_field' => 'Borrar este campo',
		'delete_hidden_complete' => 'Todas las entradas ocultas sin dependientes han sido borrados',
		'delete_hidden_note' => ' - todas las preguntas ocultas, respuestas y comentarios sin dependientes',
		'delete_hidden' => 'Borrar las entradas ocultas',
		'delete_link' => 'Borrar este enlace',
		'delete_page' => 'Borrar esta página',
		'delete_stop' => 'Parar de borrar',
		'delete_title' => 'Borrar este título',
		'delete_widget_position' => "Borrar este widget de esta posición",
		'edit_custom_page' => 'Editar página personalizada',
		'edit_field' => ' - ^1editar campo^2',
		'edit_link' => ' - ^1editar enlace^2',
		'edit_page' => ' - ^1editar página^2',
		'edit_title' => ' - ^1editar título^2',
		'emails_title' => 'Emails',
		'feed_link_example' => 'Fuente de ejemplo',
		'feed_link' => 'Fuente',
		'feeds_title' => 'Fuentes RSS',
		'field_link_url' => 'URL enlazada',
		'field_multi_line' => 'Múltiples líneas de texto',
		'field_name' => 'Nombre del campo a mostrar:',
		'field_single_line' => 'Única línea de texto',
		'field_type' => 'Tipo del campo:',
		'first' => 'Primero',
		'from_anon' => 'De anónimos:',
		'from_users' => 'De usuarios:',
		'general_title' => 'General',
		'hidden_answers_deleted' => 'Borradas ^1 de ^2 respuestas ocultas sin dependientes...',
		'hidden_comments_deleted' => 'Borrados ^1 de ^2 comentarios ocultos...',
		'hidden_questions_deleted' => 'Borradas ^1 of ^2 preguntas ocultas sin dependientes...',
		'hidden_title' => 'Ocultos',
		'ip_address_pages' => "Páginas de direcciones IP",
		'layout_title' => 'Diseño',
		'link_name' => 'Texto para el enlace:',
		'link_new_window' => 'Abrir enlace en una ventana nueva',
		'link_url' => 'URL del enlace (absoluta o relativa a la raíz de QA):',
		'lists_title' => "Listas",
		'maintenance_admin_only' => 'Tu sitio web esta en ^1maintenance^2 y es actualmente inaccesible para los usuarios normales.',
		'maximum_x' => ' (max ^)',
		'mysql_version' => 'Version MySQL:',
		'nav_links_explanation' => 'Muestra los siguientes enlaces de navegación en cada página:',
		'nav_qa_is_home' => 'Q&A (enlaces a la página de inicio)',
		'neat_urls_note' => ' (requiere un archivo ^1htaccess^2)',
		'no_classification' => 'Sin clasificar',
		'no_hidden_found' => 'No se han encontrado preguntas, respuestas o comentarios ocultos',
		'no_image_gd' => 'La versión instalada de PHP ha sido compilada sin el soporte GD para imágenes, por lo que los usuarios no pueden subir sus avatares directamente.',
		'no_link' => 'Sin enlace',
		'no_multibyte' => 'La versión instalada de PHP ha sido compilada sin el soporte a cadenas multibyte. Las búsquedas serán menos efectivas para los caracteres no romanos.',
		'no_privileges' => 'Sólo los administradores deberían acceder a esta página.',
		'not_logged_in' => 'Por favor, ^1log in^2 como administrador para acceder a esta página.',
		'opposite_main_menu' => 'Menú opuesto de pestañas en la zona superior',
		'options_reset' => 'Opciones reseteadas',
		'options_saved' => 'Opciones guardadas',
		'page_already_used' => 'Ya esta en uso por una página',
		'page_content_html' => 'Contenido para mostrar en la página (permitido HTML):',
		'page_default_slug' => 'página-^',
		'page_heading' => 'Cabecera para mostrar en la zona superior de la página:',
		'page_name' => 'Nombre de la página (también usado para la pestaña o enlace):',
		'page_slug' => 'Alias para la página (fragmento URL):',
		'pages_explanation' => 'Presiona el botón \'Añadir página\' para añadir contenido personalizado en tu sitio QA, o \'Añadir enlace\' para enlazar con cualquier otra página web.',
		'pages_title' => 'Páginas',
		'permissions_title' => 'Permisos',
		'php_version' => 'Versión PHP:',
		'plugin_pages_explanation' => 'Las siguientes páginas están disponible a través de plugins:',
		'plugins_title' => 'Plugins',
		'points_defaults_shown' => 'Se muestran los valores por defecto pero AÚN NO SE HAN APLICADO:',
		'points_required' => 'Puntos necesarios para recibir un título:',
		'points_title' => 'Puntos',
		'points' => 'puntos',
		'position' => 'Posición:',
		'posting_title' => 'Publicación',
		'profile_fields' => 'Campos extra en el perfil de usuario:',
		'q2a_db_version' => 'Versión de la Base de Datos Q2A:',
		'q2a_latest_version' => 'Última versión Q2A:',
		'q2a_version' => 'Versión Question2Answer:',
		'question_lists' => "Listas de preguntas",
		'question_pages' => "Páginas de preguntas",
		'recalc_categories_complete' => 'Todas las categorías se han recalculado correctamente.',
		'recalc_categories_note' => ' - para las entradas en categorías y cómputo de categorías',
		'recalc_categories_recounting' => "Recalculando las preguntas para ^1 de ^2 categorías...",
		'recalc_categories_updated' => 'Recalculados para ^1 de ^2 respuestas y comentarios...',
		'recalc_categories' => 'Recalcular categorías',
		'recalc_points_complete' => 'Todos los puntos de los usuarios se han recalculado correctamente.',
		'recalc_points_note' => ' - para la clasificación de usuarios y puntos mostrados',
		'recalc_points_recalced' => 'Recalculado para ^1 de ^2 usuarios...',
		'recalc_points_usercount' => 'Número total estimado de usuarios...',
		'recalc_points' => 'Recalcular los puntos de usuario',
		'recalc_posts_count' => 'Obtener el número total de preguntas, respuestas y comentarios...',
		'recalc_stop' => 'Parar recalculado',
		'recalc_categories_backpaths' => "Recalculando rutas URL ^1 de ^2 categorías...",
		'recent_hidden_title' => 'Preguntas con contenido ocultado recientemente',
		'recount_posts_complete' => 'Todas las preguntas y respuestas se han recontado correctamente',
		'recount_posts_note' => ' - el número de respuestas y votos para cada entrada',
		'recount_posts_stop' => 'Parar recuento',
		'recount_posts' => 'Recontar preguntas y respuestas',
		'reindex_posts_complete' => 'Todas las preguntas, respuestas y comentarios se han reindexado correctamente.',
		'reindex_posts_reindexed' => 'Reindexadas ^1 de ^2 preguntas, respuestas y comentarios...',
		'reindex_posts_wordcounted' => 'Recontados ^1 de ^2 palabras...',
		'requires_q2a_version' => 'Desactivado - necesitas Question2Answer ^ o posterior',
		'reset_options_button' => 'Resetear a valores por defecto',
		'save_options_button' => 'Guardar opciones',
		'save_recalc_button' => 'Guardar y recalcular',
		'show_defaults_button' => 'Mostrar resultados',
		'slug_bad_chars' => 'El alias no debe incluir estos caracteres: ^',
		'slug_reserved' => 'Este alias esta reservado para ser usado por otra página',
		'spam_title' => 'Spam',
		'stats_title' => 'Estadísticas',
		'stop_recalc_warning' => 'Una limpieza de la Base de Datos esta en proceso. Si cierras esta página ahora, la operación será interrumpida.',
		'tags_and_categories' => 'Etiquetas y categorías',
		'tags_not_shown' => 'Algunas preguntas contienen etiquetas que no se mostrarán.',
		'tags' => 'Etiquetas',
		'tag_pages' => "Páginas de etiquetas",
		'title_already_used' => 'Este valor ya es utilizado por otro título',
		'total_as' => 'Respuestas totales:',
		'total_cs' => 'Comentarios totales:',
		'total_qs' => 'Preguntas totales:',
		'unnamed_plugin' => 'Plugin sin nombre',
		'upgrade_db' => 'Tu Base de Datos Question2Answer necesita ^1upgraded^2 para esta versión.',
		'url_format_note' => 'Opciones con la etiqueta ^ funcionan en la configuración de tu sitio/s web. Para una mejor optimización en los motores de búsqueda (SEO), utiliza la primera opción ^ disponible.',
		'user_title' => 'Título de usuario (permite HTML):',
		'user_titles' => 'Títulos de usuario basados en puntos:',
		'user_pages' => "Páginas de usuario",
		'users_active' => 'Usuarios activos:',
		'users_must_have' => "Los usuarios deben tener",
		'users_posted' => 'Usuarios que han participado:',
		'users_registered' => 'Usuarios registrados:',
		'users_title' => 'Usuarios',
		'users_voted' => 'Usuarios que han votado:',
		'viewing_title' => 'Visualización',
		'widget_all_pages' => "Mostrar el widget en esta posición en todas las páginas disponibles",
		'widget_global_options' => " - ^1edita opciones globales^2",
		'widget_name' => "Nombre del widget:",
		'widget_no_positions' => "Este widget ha sido añadido en todas las posiciones disponibles.",
		'widget_not_available' => "Este widget no está disponible. Esto podría ser porque el plugin que provee este widget no esté instalado.",
		'widget_pages_explanation' => "Mostrar este widget en esta posición en las siguientes páginas:",
		'moderate_title' => "Moderar",
		'cancel_mailing_button' => "Cancelar Mailing",
		'characters' => "caracteres",
		'check_language_suffix' => " - ^1chequear archivos de lenguaje^2",
		'emails_per_minute' => "emails por minuto",
		'flagged_title' => "Marcadas",
		'hotness_factors' => "Importancia relativa de preguntas más activas:",
		'mailing_complete' => "El mailing está completo",
		'mailing_explanation' => "Los usuarios podrán de-suscribirse en la página de su cuenta.",
		'mailing_progress' => "Mailing completo para ^1 de ^2 usuarios...",
		'mailing_title' => "Mailing",
		'mailing_unsubscribe' => "Un enlace para de-suscribirse será añadido al final de cada mensaje.",
		'module_x_database_init' => "El módulo ^1 ^2 requiere ^3inicialización de la base de datos^4.",
		'most_flagged_title' => "Contenido marcado",
		'no_approve_found' => "No hay contenido esperando aprobación",
		'no_flagged_found' => "No hay contenido marcado",
		'options' => "opciones",
		'pause_mailing_button' => "Pausar Mailing",
		'per_ip_hour' => "por IP/hora",
		'per_user_hour' => "por usuario/hora",
		'permit_to_view' => "Visible para:",
		'pixels' => "pixeles",
		'plugin_module' => " (módulo de plugin: ^)",
		'q2a_build_date' => "Fecha de construcción:",
		'q2a_db_size' => "Tamaño de la base de datos:",
		'recent_approve_title' => "Contenido reciente esperando aprobación",
		'recount_posts_as_recounted' => "Respuestas y nivel de actividad recontadas para ^1 de ^2 entradas...",
		'recount_posts_votes_recounted' => "Votos y marcas recontadas para ^1 de ^2 entradas...",
		'refill_events_complete' => "Todas las secuencias de eventos fueron rellenadas con éxito",
		'refill_events_note' => " - para la lista de actualizaciones de cada usuario",
		'refill_events_refilled' => "Rellenado para ^1 de ^2 preguntas...",
		'refill_events' => "Rellenar secuencia de eventos",
		'reindex_content' => "Reindexar contenido",
		'reindex_content_note' => " - para sugerencias de búsquedas y preguntas relacionadas",
		'reindex_content_stop' => "Parar de reindexar",
		'reindex_pages_reindexed' => "Reindexado ^1 de ^2 páginas...",
		'requires_php_version' => "Desabilitado - requiere PHP ^ o posterior",
		'resume_mailing_button' => "Reanudar Mailing",
		'send_test_button' => "Enviarme un Test",
		'start_mailing_button' => "Comenzar Mailing",
		'test_sent_to_x' => "El mensaje de test fue enviado a ^",
		'top_level_categories' => "Categorías de nivel superior:",
		'version_get_x' => "obtener ^",
		'version_requires_php' => "^1 requiere PHP ^2",
		'version_requires_q2a' => "^1 requiere Q2A ^2",
		'version_latest_unknown' => "desconocida la última",
		'version_latest' => "la última",
		'widgets_explanation' => "Widgets disponibles:",
		'blobs_directory_error' => "El directorio ^ definido como QA_BLOBS_DIRECTORY no tiene permisos de escritura para el servidor web.",
		'blobs_move_complete' => "Se ha completado la migración de imágenes y documentos.",
		'blobs_move_moved' => "Migración ^1 de ^2 imágenes y documentos subidos",
		'blobs_stop' => "Detener la migración",
		'blobs_to_db' => "Llevar blobs a la base de datos",
		'blobs_to_db_note' => "- migrar todas las imágenes y documentos subidos desde archivos en el disco a la base de datos",
		'blobs_to_disk' => "Llevar blobs al disco",
		'blobs_to_disk_note' => "- migrar todas las imágenes y documentos desde la base de datos a archivos en el disco",
		'block_button' => "bloque",
		'form_security_expired' => "El código de seguridad del formulario expiró - por favor intente de nuevo",
		'approve_users_title' => "Aprobar usuarios",
		'no_unapproved_found' => "Ningún usuario está esperando aprobación",
		'registration_fields' => "añadir campos de registro",
		'show_on_register_form' => "Mostrar campo en el formulario de registro de usuarios",
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
